In [481]:
#!g1.1
loader = ModelLoader()
a = predicted('(отношение к клиенту просто ужас и такие как А. Б-ва не должны работать в принципе с клиентами.')
a

[0.9985833168029785, 0.0003781790437642485, 0.0010384791530668736]

In [518]:
#!g1.1
data = pd.read_csv('/home/jupyter/mnt/s3/main-data/dataset/1sentencenewtest.csv')
data

     Unnamed: 0                                                  0
0             0  15.03.2022 обратился на горячую линию для закр...
1             1  Уже который год в ТКБ не решается "глобальная ...
2             2                                        Добрый день
3             3  Добрый день Сегодня, зайдя в свой личный кабин...
4             4  Обслуживаюсь в Тинькофф пару лет, возникла жес...
..          ...                                                ...
944         944  Отвратительный сервис и отношение к клиентам! ...
945         945  28.04.2022 обратилась в банк о возможности пер...
946         946  В начале 2021 года была акция по выплате 8% ке...
947         947   Бездействие банка и некомпетентность сотрудников
948         948  Потрачено 5 часов чтобы произвести оплату за о...

[949 rows x 2 columns]

In [519]:
#!g1.1
# data.drop(columns=['negative', 'positive', 'neutral'])
# data

In [520]:
#!g1.1
data['+'] = 0.0
data['-'] = 0.0
data['?'] = 0.0
# data = [['Unnamed: 0', '0', '+', '-', '?']]
data = data.reindex(columns=['Unnamed: 0','0','+','-','?'])
print(data.head())
data.shape[0]

for i in range(data.shape[0]):
    res = predicted(data['0'][i])
    data['+'][i] = res[1]
    data['-'][i] = res[0]
    data['?'][i] = res[2]
data.to_csv('/home/jupyter/mnt/s3/main-data/dataset/test_res.csv')
data

   Unnamed: 0                                                  0    +    -    ?
0           0  15.03.2022 обратился на горячую линию для закр...  0.0  0.0  0.0
1           1  Уже который год в ТКБ не решается "глобальная ...  0.0  0.0  0.0
2           2                                        Добрый день  0.0  0.0  0.0
3           3  Добрый день Сегодня, зайдя в свой личный кабин...  0.0  0.0  0.0
4           4  Обслуживаюсь в Тинькофф пару лет, возникла жес...  0.0  0.0  0.0

<ipython-input-130-32ff78d34d3f>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['+'][i] = res[1]
<ipython-input-130-32ff78d34d3f>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['-'][i] = res[0]
<ipython-input-130-32ff78d34d3f>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['?'][i] = res[2]

     Unnamed: 0  ...         ?
0             0  ...  0.260033
1             1  ...  0.074235
2             2  ...  0.439120
3             3  ...  0.532828
4             4  ...  0.203520
..          ...  ...       ...
944         944  ...  0.011068
945         945  ...  0.336252
946         946  ...  0.729547
947         947  ...  0.011630
948         948  ...  0.047246

[949 rows x 5 columns]

In [521]:
#!g1.1
for i in range(data.shape[0]):
    res = predicted(data['0'][i])
    print(data['0'][i])
    print(res)
    print()
    if i == 10:
        break

15.03.2022 обратился на горячую линию для закрытия счет по кредиту и получения справки о закрытии и состоянии счетов на 21.12.2021
[0.5458155274391174, 0.19415108859539032, 0.26003333926200867]

Уже который год в ТКБ не решается "глобальная проблема" отправки банальной справки об остатке на счёте при запросе в приложении, веб версии и т.п
[0.920615017414093, 0.005149570293724537, 0.07423536479473114]

Добрый день
[0.3382120132446289, 0.2226680964231491, 0.43911993503570557]

Добрый день Сегодня, зайдя в свой личный кабинет я обнаружила, что из него пропала вся информация по всем моим счетам
[0.45333582162857056, 0.013836140744388103, 0.5328280329704285]

Обслуживаюсь в Тинькофф пару лет, возникла жесточайшая потребность в получении квалифицированного инвестора с возможной последующей покупкой акций акционерного общества
[0.3799504041671753, 0.41652989387512207, 0.20351967215538025]

В начале месяца прогремела новость о том, что начиная с 23го июня банк начнет снимать комиссию 12% годовых с валютных счетов
[0.8928912281990051, 0.035773541778326035, 0.07133527845144272]

Оставляю отзыв о работе персонального менеджера- Т-ч Никита
[0.12042561918497086, 0.7183060050010681, 0.16126838326454163]

После введенных ЦБ ограничений выдача наличных долларов осуществляется банком по заявке не менее чем за 20 дней
[0.9603828191757202, 0.002059010788798332, 0.03755810111761093]

Захожу на сайт ВТБ, вхожу в личный кабинет, но не могу получить инфу о движении средств на карте..
[0.9260334372520447, 0.012066883035004139, 0.06189966946840286]

Банк замечательно и быстро выдает кредит- тут все налажено ( являюсь клиентом банка с 2008 года - знаю), но вот потом - вы для банка- никто и на ваши запросы можно не отвечать
[0.37573862075805664, 0.3380582630634308, 0.2862030863761902]

Отвратительная работа банка
[0.8205274939537048, 0.07761916518211365, 0.10185334831476212]

In [ ]:
#!g1.1